### ISSUE TITLE
MultiPolyline 和 MultiPolygon 定义反了

### ISSUE THREAD

**Issue by Hanxven** [didi/vue-tmap#12]
如源码 `src/index.ts` L5, L6 所示：

![image](https://github.com/didi/vue-tmap/assets/52438792/7c09c99f-28ed-4995-977a-498253b8830f)

发布包的 ES 版本，JS 源码和 TS 类型定义，MultiPolyline 和 MultiPolygon 都是反的。UMD 包没有问题。

另外，TypeScript 类型不生效，`vue-tmap/dist/index.d.ts` 需要手动改成 `vue-tmap/dist/vue-tmap.es.d.ts` 才能被识别。

TS: 5.0.4 (Volar Takeover Mode)
Vue: 3.3.1
Vite: 4.3.5
@map-component/vue-tmap: 0.1.8

**Comment by shiye515** [comment]
可以升级到1.0.1 试一下，MultiPolyline 和 MultiPolygon  的定义错误，类型文件无法自动关联这两个问题都修复了

**Comment by Hanxven** [comment]
> 可以升级到1.0.1 试一下，MultiPolyline 和 MultiPolygon 的定义错误，类型文件无法自动关联这两个问题都修复了

感谢。
