### ISSUE TITLE
可以添加热力图的支持么

### ISSUE THREAD

**Issue by mubai576** [didi/vue-tmap#14]
可以添加热力图的支持么

**Comment by shiye515** [comment]
我们这个组件库是对[JavaScript API GL api](https://lbs.qq.com/webApi/javascriptGL/glDoc/glDocIndex)的封装。暂时没有封装[数据可视化api](https://lbs.qq.com/webApi/visualizationApi/visualizationGuide/visualizationOverview)的计划
