### ISSUE TITLE
tmap-multi-marker 不能监听 geometries array 的修改

### ISSUE THREAD

**Issue by geek981108** [didi/vue-tmap#8]
## 问题

tmap-multi-marker 不能监听 geometries array 的修改

## 可能的原因 

watch 没有deep
```js
watch(
      () => props.geometries,
      (geometries) => {
        markers.setGeometries(buildGeometries(geometries));
      },
);
```
## 延伸

styles 可能存在同样的问题

## 影响场景

考虑一个需要通过点击地图, 在地图上添加 marker 的场景, 上述问题导致 marker 不能及时更新在 UI 上

**Comment by iblq** [comment]
@geek981108  所有组件的最初设计都是不深监听 geometries 数组元素，在大数据量时，geometries 数组可能有几万几十万的元素，全部监听可能有较大的性能浪费，建议直接修改数组的引用地址解决
